#!/usr/bin/env python3
"""Build the label files the portal loads next to the CHAD-AP graph.

The graph points at external vocabularies (LOC ISO 639-2 languages, LOC MARC
countries, Getty AAT roles, CHAD-AP types) without carrying their labels.
Sampo-UI facets need a skos:prefLabel per value, so this script writes them:

  vocab/static.ttl     offline: every ISO 639-2 code (bibliographic and
                       terminology forms) via pycountry, plus role, actor
                       type and gender labels.
  vocab/countries.nt   --countries: fetches the English skos:prefLabel of
                       every LOC country IRI found in a graph file from
                       id.loc.gov (one request per code, cached: codes
                       already in the file are not fetched again).

Both files are committed, so a portal load needs no network access; rerun
--countries only when a new graph introduces new country codes.

Usage
-----
python 08_sampo_portal/triplestore/build_vocab.py
python 08_sampo_portal/triplestore/build_vocab.py --countries \\
    --graph 07_graph_materialisation/output/full/knowledge-graph_merged.nt
"""

from __future__ import annotations

import argparse
import re
import sys
import time
import urllib.request
from pathlib import Path

import pycountry

VOCAB_DIR = Path(__file__).resolve().parent / "vocab"
LOC_LANG = "http://id.loc.gov/vocabulary/iso639-2/"
LOC_COUNTRY = "http://id.loc.gov/vocabulary/countries/"
OBJ = "https://w3id.org/dharc/ontology/chad-ap/object/development/14/schema/"
SKOS_PREF = "<http://www.w3.org/2004/02/skos/core#prefLabel>"

STATIC_LABELS = {
    "http://vocab.getty.edu/aat/300025492": "author",
    "http://vocab.getty.edu/aat/300312355": "editor",
    "http://vocab.getty.edu/aat/300069831": "translator",
    "http://vocab.getty.edu/aat/300025164": "illustrator",
    f"{OBJ}Person": "Person",
    f"{OBJ}Organization": "Organisation",
    f"{OBJ}male": "male",
    f"{OBJ}female": "female",
}


def literal(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"@en'


def build_static() -> Path:
    labels = dict(STATIC_LABELS)
    for lang in pycountry.languages:
        name = getattr(lang, "name", "")
        for code in {getattr(lang, "alpha_3", None), getattr(lang, "bibliographic", None)}:
            if code and name:
                labels[f"{LOC_LANG}{code}"] = name
    VOCAB_DIR.mkdir(parents=True, exist_ok=True)
    out = VOCAB_DIR / "static.ttl"
    with out.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Generated by build_vocab.py; do not edit by hand.\n")
        for iri in sorted(labels):
            fh.write(f"<{iri}> {SKOS_PREF} {literal(labels[iri])} .\n")
    print(f"static labels: {len(labels)} -> {out}")
    return out


def build_countries(graph: Path, delay: float) -> Path:
    out = VOCAB_DIR / "countries.nt"
    known: dict[str, str] = {}
    if out.exists():
        for line in out.read_text(encoding="utf-8").splitlines():
            m = re.match(r"<([^>]+)> \S+ (\".*\"@en) \.$", line)
            if m:
                known[m.group(1)] = m.group(2)

    wanted: set[str] = set()
    pattern = re.compile(re.escape(LOC_COUNTRY) + r"[a-z]+")
    with graph.open(encoding="utf-8") as fh:
        for line in fh:
            wanted.update(pattern.findall(line))
    todo = sorted(wanted - set(known))
    print(f"country IRIs in graph: {len(wanted)}, already labelled: {len(wanted) - len(todo)}, to fetch: {len(todo)}")

    for i, iri in enumerate(todo, 1):
        url = f"{iri}.skos.nt".replace("http://", "https://", 1)
        try:
            with urllib.request.urlopen(url, timeout=30) as resp:
                body = resp.read().decode("utf-8")
        except Exception as exc:  # keep going; a missing label falls back to the code
            print(f"  [{i}/{len(todo)}] {iri}: {exc}")
            continue
        m = re.search(rf"^<{re.escape(iri)}> {re.escape(SKOS_PREF)} (\".*\"@en) \.$", body, re.M)
        if m:
            known[iri] = m.group(1)
            print(f"  [{i}/{len(todo)}] {iri}: {m.group(1)}")
        time.sleep(delay)

    VOCAB_DIR.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="\n") as fh:
        for iri in sorted(known):
            fh.write(f"<{iri}> {SKOS_PREF} {known[iri]} .\n")
    print(f"country labels: {len(known)} -> {out}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--countries", action="store_true", help="also fetch LOC country labels (network)")
    parser.add_argument("--graph", type=Path,
                        default=Path("07_graph_materialisation/output/sample/knowledge-graph_merged.nt"),
                        help="graph file scanned for country IRIs")
    parser.add_argument("--delay", type=float, default=0.5, help="seconds between id.loc.gov requests")
    args = parser.parse_args()
    build_static()
    if args.countries:
        if not args.graph.exists():
            sys.exit(f"graph not found: {args.graph}")
        build_countries(args.graph, args.delay)


if __name__ == "__main__":
    main()
